### ISSUE TITLE
A small issue with sabnzbd's install

### ISSUE THREAD

**Issue by Sharker51** [projetssd/ssdv2#11]
Hello,

I'm just testing the script and it seems there is a small problem with the installation of sabnzbd.
During the process, the script want to edit the ini file at "/opt/seedbox/docker/USER/sabnzbd/sabnzbd.ini", but the good path seems to be "/opt/seedbox/docker/USER/sabnzbd/config/sabnzbd.ini".

logs/ansible.log:2021-10-17 21:13:17,543 p=469 u=USER n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for file /opt/seedbox/docker/sharker/sabnzbd/sabnzbd.ini"}

I hope I'm not wrong and it will help.

Regards,

Sharker

PS: install on Debian GNU/Linux 10

**Comment by Merrick28** [comment]
Thanks, fixed by commit [af8a2628a7cb8ef3736b31930e9b50be27d21b1d](https://github.com/projetssd/ssdv2/commit/af8a2628a7cb8ef3736b31930e9b50be27d21b1d)
