### ISSUE TITLE
[Guacamole] Hostname guacd incorrect

### ISSUE THREAD

**Issue by cleme29** [projetssd/ssdv2#38]
Bonjour,

Je viens de repérer un problème sur l'application Guacamole.
En effet, le conteneur guacamole dispose d'une mauvaise configuration qui empêche la communication en websocket au conteneur guacd. Au final, aucune connexion à distance n'est possible.

J'ai retrouvé dans le conteneur guacamole, fichier /home/guacamole/.guacamole/guacamole.properties : 
--> guacd-hostname: guacamole

or l'hostname devrait plutôt être celui du conteneur guacd et non lui même.

J'ai donc, pour l'instant, mis le bon hostname hardcodé dans le fichier yml d'ansible.

Avant :

https://github.com/projetssd/ssdv2/blob/f88c8457d68fca47b30e3ae332d084cae743739d/includes/dockerapps/vars/guacamole.yml#L15

Après

GUACD_HOSTNAME: "guacd"

Merci d'avance !

**Comment by Merrick28** [comment]
Corrigé

**Comment by Merrick28** [comment]
Salut, je ne l'utilise pas, donc je n'ai pas testé. J'ai corrigé comme
spécifié.

Cordialement,
Merrick
